# Change 'comments' to true for Disqus comments
#disqus:
  #comments: false
  #disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
#google-ID: ''

homepage:
- {name: '', lang: 'en-US', folder: '.', file: 'index.html'}
- {name: '', lang: 'es-CR', folder: 'es_CR', file: 'index.html'}

menu:
- {name: 'Blog', lang: 'en-US', folder: 'pages', file: 'blog.html'}
- {name: 'Resume', lang: 'en-US', folder: 'pages', file: 'resume.html'}
- {name: 'Contact', lang: 'en-US', folder: 'pages', file: 'contact.html'}
- {name: 'Blog', lang: 'es-CR', folder: 'es_CR/pages', file: 'blog.html'}
- {name: 'Resume', lang: 'es-CR', folder: 'es_CR/pages', file: 'resume.html'}
- {name: 'Contacto', lang: 'es-CR', folder: 'es_CR/pages', file: 'contact.html'}


# language inventory

languages:
  langOption:
    en-US: "en"
    es-CR: "es"


# Footer Translation
f:
  footer-article:
    en-US: "A personal presentation, a portfolio and where I store my self-learning guides."
    es-CR: "Una presentacion personal, un portafolio y donde guardo mis guias autodidacticas."

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'fab fa-twitter', link: 'https://twitter.com/aroblesfuentes'}
- {icon: 'fas fa-envelope', link: 'mailto:adrian@roblesadrian.com'}
- {icon: 'fab fa-github', link: 'https://github.com/adrian-robles'}
- {icon: 'fab fa-linkedin-in', link: 'https://www.linkedin.com/in/aroblesfuentes/'}
#- {icon: 'fas fa-rss', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

